config/routes.rb
Rails.application.routes.draw do

  resources :feedbacks
  resources :beta_codes
  resources :date_stories
  resources :users
  resources :venues

  get 'users/fbUser/:fbAccessToken' => 'users#showfbUser'
  put 'users/fbUser/:fbAccessToken' => 'users#fbUserUpdate'
  get 'venues/polaroid/all' => 'venues#polaroid'
  get 'venues/cellVenue/all' => 'venues#cellVenue'
  get 'beta_codes/bCode/:code' => 'beta_codes#bCode'

  root 'venues#index'
  

end

app/models/beta_code.rb
class BetaCode < ActiveRecord::Base
end

app/controllers/beta_codes_controller.rb
class BetaCodesController < ApplicationController
  before_action :set_beta_code, only: [:show, :edit, :update, :destroy]

  # GET /beta_codes
  # GET /beta_codes.json
  def index
    @beta_codes = BetaCode.all
  end

  # GET /beta_codes/1
  # GET /beta_codes/1.json
  def show
  end

  # GET /beta_codes/bCode/:code.json
  # GET /beta_codes/bCode/:code.json
  def bCode
    @beta_code = BetaCode.find_by(code: params[:code]) 
    @beta_code.update_column(:user_count, @beta_code.user_count+1)
  end

  # GET /beta_codes/new
  def new
    @beta_code = BetaCode.new
  end

  # GET /beta_codes/1/edit
  def edit
  end

  # POST /beta_codes
  # POST /beta_codes.json
  def create
    @beta_code = BetaCode.new(beta_code_params)

    respond_to do |format|
      if @beta_code.save
        format.html { redirect_to @beta_code, notice: 'Beta code was successfully created.' }
        format.json { render :show, status: :created, location: @beta_code }
      else
        format.html { render :new }
        format.json { render json: @beta_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beta_codes/1
  # PATCH/PUT /beta_codes/1.json
  def update
    respond_to do |format|
      if @beta_code.update(beta_code_params)
        format.html { redirect_to @beta_code, notice: 'Beta code was successfully updated.' }
        format.json { render :show, status: :ok, location: @beta_code }
      else
        format.html { render :edit }
        format.json { render json: @beta_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beta_codes/1
  # DELETE /beta_codes/1.json
  def destroy
    @beta_code.destroy
    respond_to do |format|
      format.html { redirect_to beta_codes_url, notice: 'Beta code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beta_code
      @beta_code = BetaCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beta_code_params
      params.require(:beta_code).permit(:code, :user_max, :user_count)
    end
end

app/helpers/beta_codes_helper.rb
module BetaCodesHelper
end

app/views/beta_codes/_form.html.erb
<%= form_for(@beta_code) do |f| %>
  <% if @beta_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beta_code.errors.count, "error") %> prohibited this beta_code from being saved:</h2>

      <ul>
      <% @beta_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :user_max %><br>
    <%= f.number_field :user_max %>
  </div>
  <div class="field">
    <%= f.label :user_count %><br>
    <%= f.number_field :user_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beta_codes/bCode.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @beta_code.code %>
</p>

<p>
  <strong>User max:</strong>
  <%= @beta_code.user_max %>
</p>

<p>
  <strong>User count:</strong>
  <%= @beta_code.user_count %>
</p>

<%= link_to 'Edit', edit_beta_code_path(@beta_code) %> |
<%= link_to 'Back', beta_codes_path %>

app/views/beta_codes/edit.html.erb
<h1>Editing Beta Code</h1>

<%= render 'form' %>

<%= link_to 'Show', @beta_code %> |
<%= link_to 'Back', beta_codes_path %>

app/views/beta_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beta Codes</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>User max</th>
      <th>User count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beta_codes.each do |beta_code| %>
      <tr>
        <td><%= beta_code.code %></td>
        <td><%= beta_code.user_max %></td>
        <td><%= beta_code.user_count %></td>
        <td><%= link_to 'Show', beta_code %></td>
        <td><%= link_to 'Edit', edit_beta_code_path(beta_code) %></td>
        <td><%= link_to 'Destroy', beta_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beta code', new_beta_code_path %>

app/views/beta_codes/new.html.erb
<h1>New Beta Code</h1>

<%= render 'form' %>

<%= link_to 'Back', beta_codes_path %>

app/views/beta_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @beta_code.code %>
</p>

<p>
  <strong>User max:</strong>
  <%= @beta_code.user_max %>
</p>

<p>
  <strong>User count:</strong>
  <%= @beta_code.user_count %>
</p>

<%= link_to 'Edit', edit_beta_code_path(@beta_code) %> |
<%= link_to 'Back', beta_codes_path %>