config/routes.rb
Rails.application.routes.draw do

  resources :feedbacks
  resources :beta_codes
  resources :date_stories
  resources :users
  resources :venues

  get 'users/fbUser/:fbAccessToken' => 'users#showfbUser'
  put 'users/fbUser/:fbAccessToken' => 'users#fbUserUpdate'
  get 'venues/polaroid/all' => 'venues#polaroid'
  get 'venues/cellVenue/all' => 'venues#cellVenue'
  get 'beta_codes/bCode/:code' => 'beta_codes#bCode'

  root 'venues#index'
  

end

app/models/venue.rb
class Venue < ActiveRecord::Base
	has_many :date_stories
	scope :starts_with, -> (name) { where("name like ?", "#{name}%")}
	has_attached_file :polaroid_image, :styles => { :original => "2080x1600"}
	has_attached_file :thumbnail_image, :styles => { :original => "256x256"}
	has_attached_file :venue_image_1, :styles => { :original => "2048x2048"}
	has_attached_file :venue_image_2, :styles => { :original => "2048x2048"}
	has_attached_file :venue_image_3, :styles => { :original => "2048x2048"}
	has_attached_file :venue_image_4, :styles => { :original => "2048x2048"}
	has_attached_file :venue_image_5, :styles => { :original => "2048x2048"}
	validates_attachment :polaroid_image, :thumbnail_image, :venue_image_1, :venue_image_2, :venue_image_3, :venue_image_4, :venue_image_5, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.where(nil)
    @venues = @venues.starts_with(params[:starts_with]) if params[:starts_with].present?
    if params[:starts_with].blank?
      @venues = Venue.order('name ASC')
    end
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  #THIS IS WHERE OUR ALGORITHM GOES
  # GET /venues/polaroid/all
  # GET /venues/polaroid/all.json
  def polaroid
    if params[:neighborhood].blank? || params[:user_fbAccessToken].blank?
      @venues = Venue.all.limit(5)
    else
      neighborhood_array = params[:neighborhood].split('Q')
      puts "Neigh array: ", neighborhood_array
      @venues = Venue.where(neighborhood: neighborhood_array)

      if(params[:coffee] == "YES" || params[:mood].blank? || params[:mood] == "Not-Picky")
        puts "Not Picky"
      else
        @venues = @venues.where(mood: params[:mood])
      end
      @venues = @venues.where(dinner: params[:dinner]) unless params[:dinner].blank?
      @venues = @venues.where(dessert: params[:dessert]) unless params[:dessert].blank?
      @venues = @venues.where(drinks: params[:drinks]) unless params[:drinks].blank?
      @venues = @venues.where(coffee: params[:coffee]) unless params[:coffee].blank?
      if(@venues.size < 5)
        @venues = Venue.all.limit(5)
        return
      end
      user = User.find_by(fbAccessToken: params[:user_fbAccessToken]) unless params[:user_fbAccessToken].blank?
      venueHash = Hash.new
      score_sum = 0
      @venues.each{
        |v|
        puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
        puts v.name
        score = 100
        unless user.nil? || user.blank?
          unless user.favorites.nil?
            if user.favorites.include? v.id.to_s
              puts "THIS VENUE IS A FAVORITE"
              score *= 0.2
            elsif !user.favorites.include? v.id.to_s
              puts "THIS VENUE NOT A FAVORITE"
              score *= 1.5
            end
          end
          unless user.bloved_venues.nil?
              if user.bloved_venues.include? v.id.to_s
                puts "THE USER BLOVED THIS VENUE"
                score *= 0.5
              end
          end
        end
        if params[:date_day].include?("Sun") && v.sunday_special.length > 1
          score *= 2
        elsif params[:date_day].include?("Mon") && v.monday_special.length > 1
          score *= 2
        elsif params[:date_day].include?("Tue") && v.tuesday_special.length > 1
          score *= 2
        elsif params[:date_day].include?("Wed") && v.wednesday_special.length > 1
          score *= 2
        elsif params[:date_day].include?("Thu") && v.thursday_special.length > 1
          puts "SPECIAL"
          score *= 2
        elsif params[:date_day].include?("Fri") && v.friday_special.length > 1
          puts "FRI SPECI"
          score *= 2
        elsif params[:date_day].include?("Sat") && v.saturday_special.length > 1
          score *= 2
        end
        score += v.blove_count.to_f
        venueHash[v] = score
        puts score
        score_sum += score
      }
      puts "Score Sum " + score_sum.to_s
      previous_range_endpoint = 0
      # venueHash = Hash[venueHash.sort_by{|k, v| v}.reverse]
      venueHash.each{
        |vName, vScore|
        tempScore = vScore
        venueHash[vName] = previous_range_endpoint...previous_range_endpoint+vScore/score_sum
        previous_range_endpoint += tempScore/score_sum
        puts "#{vName.name}, #{vScore}"
      }
      @venues.clear
      iterationCount = 0
      while(@venues.size < 5)
        iterationCount += 1
        puts "Iteration count #{iterationCount}"
        venueHash.each{
          |venue, vRange|
          randNumber = Random.rand(1.0)
          if(iterationCount > 100 || (vRange.include?(randNumber) && !@venues.include?(venue)))
            @venues.push(venue)
            puts "Random number: #{randNumber} includes #{venue.name}"
          end
        }
      end
    end
  end

  # GET /venues/cell/all
  # GET /venues/cell/all.json
  def cellVenue
    @venues = Venue.where(id: params[:id]) if params[:id].present?
    @venues = Venue.starts_with(params[:starts_with]) if params[:starts_with].present?

  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)
    @venue.blove_count = 0
    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name, :date_type, :price_rating, :neighborhood, :address, :blove_count, :dinner, :drinks,
        :dessert, :coffee, :mood, :date_day, :user_fbAccessToken, :menu_link, :reservation_link,
        :polaroid_description, :monday_special, :tuesday_special, :wednesday_special, :thursday_special, 
        :friday_special, :saturday_special, :sunday_special, :food_drink, :why_blove_heading_1, 
        :why_blove_heading_2, :why_blove_heading_3, :why_blove_description_1, :why_blove_description_2,
        :why_blove_description_3, :price_for_two,:monday_hours, :tuesday_hours, :wednesday_hours, 
        :thursday_hours, :friday_hours, :saturday_hours, :sunday_hours, :crowd, :dress_code, :parking, 
        :reservations, :atmosphere, :keep_in_mind,
        :polaroid_image, :thumbnail_image, :venue_image_1, :venue_image_2, :venue_image_3, :venue_image_4, :venue_image_5)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Main Date Type"%><br>
    <%= f.select :date_type, ['Dinner', 'Coffee', 'Drinks', 'Dessert'] %>
  </div>
  <div class="field">
    <%= f.label :neighborhood %><br>
    <%= f.select :neighborhood, ['East-Side', 'Midtown-SLASH-Downtown', 'Buckhead-SLASH-Lindbergh']%>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :price_rating %><br>
    <%= f.select :price_rating, ['$', '$$', '$$$']%>
  </div>
  <div class="field">
    <%= f.label :dinner %><br>
    <%= f.select :dinner, ['NO', 'YES']%>
  </div>
  <div class="field">
    <%= f.label :drinks %><br>
    <%= f.select :drinks, ['NO', 'YES']%>
  </div>
  <div class="field">
    <%= f.label :dessert %><br>
    <%= f.select :dessert, ['NO', 'YES']%>
  </div>
  <div class="field">
    <%= f.label :coffee %><br>
    <%= f.select :coffee, ['NO', 'YES']%>
  </div>
  <div class="field">
    <%= f.label :mood %><br>
    <%= f.select :mood, ['Cozy-AND-Intimate', 'Cool-AND-Casual', 'Fun-AND-Lively', 'Not-Picky']%>
  </div>
  <div class="field">
    <%= f.label :polaroid_description %><br>
    <%= f.text_field :polaroid_description %>
  </div>

  <div class="field">
    <%= f.label :monday_special%><br>
    <%= f.text_field :monday_special %>
  </div>

  <div class="field">
    <%= f.label :tuesday_special%><br>
    <%= f.text_field :tuesday_special %>
  </div>

  <div class="field">
    <%= f.label :wednesday_special%><br>
    <%= f.text_field :wednesday_special %>
  </div>

  <div class="field">
    <%= f.label :thursday_special%><br>
    <%= f.text_field :thursday_special %>
  </div>

  <div class="field">
    <%= f.label :friday_special%><br>
    <%= f.text_field :friday_special %>
  </div>

  <div class="field">
    <%= f.label :saturday_special%><br>
    <%= f.text_field :saturday_special %>
  </div>

  <div class="field">
    <%= f.label :sunday_special%><br>
    <%= f.text_field :sunday_special %>
  </div>

  <div class="field">
    <%= f.label :why_blove_heading_1 %><br>
    <%= f.text_field :why_blove_heading_1 %>
  </div>

  <div class="field">
    <%= f.label :why_blove_description_1 %><br>
    <%= f.text_field :why_blove_description_1 %>
  </div>

  <div class="field">
    <%= f.label :why_blove_heading_2 %><br>
    <%= f.text_field :why_blove_heading_2 %>
  </div>

  <div class="field">
    <%= f.label :why_blove_description_2 %><br>
    <%= f.text_field :why_blove_description_2 %>
  </div>

  <div class="field">
    <%= f.label :why_blove_heading_3 %><br>
    <%= f.text_field :why_blove_heading_3 %>
  </div>

  <div class="field">
    <%= f.label :why_blove_description_3 %><br>
    <%= f.text_field :why_blove_description_3 %>
  </div>

  <div class="field">
    <%= f.label :food_drink %><br>
    <%= f.text_field :food_drink %>
  </div>
  <div class="field">
    <%= f.label :price_for_two %><br>
    <%= f.text_field :price_for_two %>
  </div>
    <div class="field">
    <%= f.label :monday_hours %><br>
    <%= f.text_field :monday_hours %>
  </div>
    </div>
    <div class="field">
    <%= f.label :tuesday_hours %><br>
    <%= f.text_field :tuesday_hours %>
  </div>
    </div>
    <div class="field">
    <%= f.label :wednesday_hours %><br>
    <%= f.text_field :wednesday_hours %>
  </div>
    </div>
    <div class="field">
    <%= f.label :thursday_hours %><br>
    <%= f.text_field :thursday_hours %>
  </div>
    </div>
    <div class="field">
    <%= f.label :friday_hours %><br>
    <%= f.text_field :friday_hours %>
  </div>
    </div>
    <div class="field">
    <%= f.label :saturday_hours %><br>
    <%= f.text_field :saturday_hours %>
  </div>
    </div>
    <div class="field">
    <%= f.label :sunday_hours %><br>
    <%= f.text_field :sunday_hours %>
  <div class="field">
    <%= f.label :crowd %><br>
    <%= f.text_field :crowd %>
  </div>
    <div class="field">
    <%= f.label :dress_code %><br>
    <%= f.select :dress_code, ['Casual (Jeans / T-shirt)', 'Stylish (Button up / Heels)', 'Dressy (Blazer / Dress)']%>
  </div>
    <div class="field">
    <%= f.label :parking %><br>
    <%= f.text_field :parking %>
  </div>
    <div class="field">
    <%= f.label :reservations %><br>
    <%= f.select :reservations, ['Yes', 'No']%>
  </div>
    <div class="field">
    <%= f.label :atmosphere %><br>
    <%= f.text_field :atmosphere %>
    </div>
  <div class="field">
    <%= f.label :keep_in_mind %><br>
    <%= f.text_field :keep_in_mind %>
  </div>
  <div class="field">
    <%= f.label :menu_link %><br>
    <%= f.text_field :menu_link %>
  </div>
  <div class="field">
    <%= f.label :reservation_link %><br>
    <%= f.text_field :reservation_link %>
  </div>
  <div class="field">
    <%= f.label :polaroid_image %><br>
    <%= f.file_field :polaroid_image %>
  </div>
    <div class="field">
    <%= f.label :thumbnail_image %><br>
    <%= f.file_field :thumbnail_image %>
  </div>
    <div class="field">
    <%= f.label :venue_image_1 %><br>
    <%= f.file_field :venue_image_1 %>
  </div>
  <div class="field">
    <%= f.label :venue_image_2 %><br>
    <%= f.file_field :venue_image_2 %>
  </div>
  <div class="field">
    <%= f.label :venue_image_3 %><br>
    <%= f.file_field :venue_image_3 %>
  </div>
  <div class="field">
    <%= f.label :venue_image_4 %><br>
    <%= f.file_field :venue_image_4 %>
  </div>
  <div class="field">
    <%= f.label :venue_image_5 %><br>
    <%= f.file_field :venue_image_5 %>
  </div>
  <div class="field">
    <%= f.label :blove_count %><br>
    <%= f.text_field :blove_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/cellVenue.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Venues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date Type</th>
      <th>Mood</th>
      <th>Price Rating</th>
      <th>Neighborhood</th>
      <th>Address</th> 
      <th>Polaroid description</th>
      <th>Blove Count</th>
      <th>Specials</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.name %></td>
        <td><%= venue.date_type%></td>
        <td><%= venue.mood %></td>
        <td><%= venue.price_rating %></td>
        <td><%= venue.neighborhood %></td>
        <td><%= venue.address %></td>
        <td><%= venue.polaroid_description %></td>
        <td><%= venue.blove_count %></td>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Venues</h1>

<table>
  <thead>
    <tr>
      <th>NAME!!!</th>
      <th>Date Type</th>
      <th>Mood</th>
      <th>Price Rating</th>
      <th>Neighborhood</th>
      <th>Address</th> 
      <th>Polaroid description</th>
      <th>Blove Count</th>
      <th>Today's Special</th>
      <th>Food drink</th>
      <th>Why blove</th>
      <th>Price for two</th>
      <th>Hours</th>
      <th>Details table</th>
      <th>Date experience</th>
      <th>Keep in mind</th>
      <th>Date Stories</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.name %></td>
        <td>
        <% if venue.dinner == 'YES' %>
            <%= "Dinner" %>
        <% end %>
        <% if venue.drinks == 'YES' %>
            <%= "Drinks" %>
        <% end %>
        <% if venue.coffee == 'YES' %>
            <%= "Coffee" %>
        <% end %>
        <% if venue.dessert == 'YES' %>
            <%= "Dessert" %>
        <% end %>     
        </td>
        <td><%= venue.mood %></td>
        <td><%= venue.price_rating %></td>
        <td><%= venue.neighborhood %></td>
        <td><%= venue.address %></td>
        <td><%= venue.polaroid_description %></td>
        <td><%= venue.blove_count %></td>
        <% if DateTime.current.wday == 0 %>
          <td><%= venue.sunday_special %></td>
        <% elsif DateTime.current.wday == 1 %>
          <td><%= venue.monday_special %></td>
        <% elsif DateTime.current.wday == 2 %>
          <td><%= venue.tuesday_special %></td>
        <% elsif DateTime.current.wday == 3 %>
          <td><%= venue.wednesday_special %></td>
        <% elsif DateTime.current.wday == 4 %>
          <td><%= venue.thursday_special %></td>
        <% elsif DateTime.current.wday == 5 %>
          <td><%= venue.friday_special %></td>
        <% elsif DateTime.current.wday == 6 %>
          <td><%= venue.saturday_special %></td>
        <% end %>
        <td><%= venue.food_drink %></td>
        <td><%= venue.why_blove_heading_1 %></td>
        <td><%= venue.price_for_two %></td>
        <td><%= venue.monday_hours %></td>
        <td><%= venue.details_table %></td>
        <td><%= venue.date_experience %></td>
        <td><%= venue.keep_in_mind %></td>
          <% venue.date_stories.each do |story| %>
          <td><%= link_to story.storyText, story%></td>
          <% end %>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/polaroid.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Venues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mood</th>
      <th>Price Rating</th>
      <th>Neighborhood</th>
      <th>Address</th> 
      <th>Polaroid description</th>
      <th>Blove Count</th>
      <th>Today's Special</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.name %></td>
        <td><%= venue.mood %></td>
        <td><%= venue.price_rating %></td>
        <td><%= venue.neighborhood %></td>
        <td><%= venue.address %></td>
        <td><%= venue.polaroid_description %></td>
        <td><%= venue.blove_count %></td>
        <% if DateTime.current.wday == 0 %>
          <td><%= venue.sunday_special %></td>
        <% elsif DateTime.current.wday == 1 %>
          <td><%= venue.monday_special %></td>
        <% elsif DateTime.current.wday == 2 %>
          <td><%= venue.tuesday_special %></td>
        <% elsif DateTime.current.wday == 3 %>
          <td><%= venue.wednesday_special %></td>
        <% elsif DateTime.current.wday == 4 %>
          <td><%= venue.thursday_special %></td>
        <% elsif DateTime.current.wday == 5 %>
          <td><%= venue.friday_special %></td>
        <% elsif DateTime.current.wday == 6 %>
          <td><%= venue.saturday_special %></td>
        <% end %>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @venue.name %>
</p>

<p>
  <strong>Polaroid Image:</strong>
    <%= image_tag @venue.polaroid_image.url %>
</p>

<p>
<strong>Thumbnail Image:</strong>
    <%= image_tag @venue.thumbnail_image.url %>
</p>

<p>
  <strong>Venue Image 1:</strong>
    <%= image_tag @venue.venue_image_1.url %>
</p>
<p>
  <strong>Venue Image 2:</strong>
    <%= image_tag @venue.venue_image_2.url %>
</p>
<p>
  <strong>Venue Image 3:</strong>
    <%= image_tag @venue.venue_image_3.url %>
</p>
<p>
  <strong>Venue Image 4:</strong>
    <%= image_tag @venue.venue_image_4.url %>
</p>
<p>
  <strong>Venue Image 5:</strong>
    <%= image_tag @venue.venue_image_5.url %>
</p>

<p>
  <strong>Mood:</strong>
  <%= @venue.mood %>
</p>

<p>
  <strong>Price Rating:</strong>
  <%= @venue.price_rating %>
</p>

<p>
  <strong>Neighborhood:</strong>
  <%= @venue.neighborhood %>
</p>

<p>
  <strong>Address:</strong>
  <%= @venue.address %>
</p>

<p>
  <strong>Polaroid description:</strong>
  <%= @venue.polaroid_description %>
</p>

<p>
  <strong>Blove Count:</strong>
  <%= @venue.blove_count %>
</p>

<p>
  <strong> Today's Special: </strong>
<% if DateTime.current.wday == 0 %>
  <%= @venue.sunday_special %>
<% elsif DateTime.current.wday == 1 %>
  <%= @venue.monday_special %>
<% elsif DateTime.current.wday == 2 %>
  <%= @venue.tuesday_special %>
<% elsif DateTime.current.wday == 3 %>
  <%= @venue.wednesday_special %>
<% elsif DateTime.current.wday == 4 %>
  <%= @venue.thursday_special %>
<% elsif DateTime.current.wday == 5 %>
  <%= @venue.friday_special %>
<% elsif DateTime.current.wday == 6 %>
  <%= @venue.saturday_special %>
<% end %>

<p>
  <strong>Food drink:</strong>
  <%= @venue.food_drink %>
</p>

<p>
  <strong>Why blove:</strong>
  <%= "H1:   " + @venue.why_blove_heading_1 %>
  <%= "D1:   " + @venue.why_blove_description_1 %><br>
  <%= "H2:   " + @venue.why_blove_heading_2 %>
  <%= "D2:   " + @venue.why_blove_description_2 %><br>
  <%= "H3:   " + @venue.why_blove_heading_3 %>
  <%= "D3:   " + @venue.why_blove_description_3 %>

</p>

<p>
  <strong>Price for two:</strong>
  <%= @venue.price_for_two %>
</p>

<p>
  <strong>Hours:</strong>
  <%= 'Monday: ' + @venue.monday_hours %>
  <%= 'Tuesday: ' + @venue.tuesday_hours %>
  <%= 'Wednesday: ' + @venue.wednesday_hours %>
  <%= 'Thursday: ' + @venue.thursday_hours %>
  <%= 'Friday: ' + @venue.friday_hours %>
  <%= 'Saturday: ' + @venue.saturday_hours %>
  <%= 'Sunday: ' + @venue.sunday_hours %>

</p>

<p>
  <strong>Details table:</strong>
  <%= @venue.details_table %>
</p>

<p>
  <strong>Date experience:</strong>
  <%= @venue.date_experience %>
</p>

<p>
  <strong>Keep in mind:</strong>
  <%= @venue.keep_in_mind %>
</p>

<p>
  <strong>Date Stories:</strong>
  <%= @venue.date_stories %>
</p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>