config/routes.rb
Rails.application.routes.draw do

  resources :feedbacks
  resources :beta_codes
  resources :date_stories
  resources :users
  resources :venues

  get 'users/fbUser/:fbAccessToken' => 'users#showfbUser'
  put 'users/fbUser/:fbAccessToken' => 'users#fbUserUpdate'
  get 'venues/polaroid/all' => 'venues#polaroid'
  get 'venues/cellVenue/all' => 'venues#cellVenue'
  get 'beta_codes/bCode/:code' => 'beta_codes#bCode'

  root 'venues#index'
  

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	belongs_to :user
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)
    fUser = User.find_by(fbAccessToken: feedback_params[:user_fbAccessToken])
    @feedback.user = fUser unless fUser.nil? || fUser.blank? 
    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:feedback_text, :user, :user_fbAccessToken)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :feedback_text %><br>
    <%= f.text_field :feedback_text %>
  </div>
  <div class="field">
    <%= f.label :user_fbAccessToken %><br>
    <%= f.text_field :user_fbAccessToken %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Feedback text</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.feedback_text %></td>
        <%# <td><%= link_to feedback.user.name, feedback.user %></td> %>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feedback text:</strong>
  <%= @feedback.feedback_text %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>